### ISSUE TITLE
Installation / Usage

### ISSUE THREAD

**Issue by tpitman** [DavidMoritz/rcv#3]
Sorry if this is a stupid question, but can you tell me how to use the RCV repository on an actual web server?

I am running apache2 with php7 (can install php5 if needed).

**Comment by DavidMoritz** [comment]
yeah! I probably could have made this more clear. There is a file called "config_sample.php" and this needs to be renamed to "config.php" (which is ignored) and input with your credentials to the location of the mysql database. Once you have that, the api should work.

**Comment by tpitman** [comment]
Super fast response. Awesome. What comes next? I probably need to write some html to call the php, right?

**Comment by tpitman** [comment]
Any chance I could get a copy of your site code or can the api stand on its own? I am getting errors about things not existing.

**Comment by DavidMoritz** [comment]
You shouldn't, no. All the html is ready, but it needs to be built by node

**Comment by DavidMoritz** [comment]
npm install
grunt

**Comment by DavidMoritz** [comment]
https://rankedchoices.com/

**Comment by tpitman** [comment]
Building now. Hopefully I have the right versions of stuff. Getting some warnings. I am trying to do this on a Raspberry Pi with Raspbian (Debian based). Crossing fingers...

Thanks again for the quick responses.

**Comment by tpitman** [comment]
I did npm install and it install a bunch of stuff. I then type grunt and it says it can't find it. I tried npm install grunt and it install grunt, so not sure what now.

**Comment by DavidMoritz** [comment]
npm install -g grunt-cli

**Comment by DavidMoritz** [comment]
I appreciate you being the guinea pig here. This clearly was not ready for consumption yet. I've tried doing a fresh pull and install and seeing the errors you are referring to. I'm making changes on the fly as well

**Comment by tpitman** [comment]
It is stuck here:

Running "jade:compile" (jade) task
>> 1 file created.

Running "less:dev" (less) task
>> 1 stylesheet created.

Running "copy:copy" (copy) task
Copied 27 files

Running "replace:dev" (replace) task
>> 1 replacement in 1 file.

Running "pleeease:dev" (pleeease) task

Running "concat:js" (concat) task

Running "jshint:all" (jshint) task

✔ No problems


Running "watch" task
Waiting...

If I browse to the "dist" folder I get the index.html, but it is blank even though the source shows a bunch of stuff.

**Comment by DavidMoritz** [comment]
that's where I am at too. The "missing" files are not being pathed correctly. I'm working on it at the moment. 
Again, I appreciate you bringing this to my attention. Give me 24 hours and I'll try to get it consumption worthy. In the meantime, feel free to tinker with it and if you find any answers, I'd like to hear them. RankedChoices.com is hosted on a LAMP stack shared hosting server, so I have "localhost" has the db location. I have tested this with an external db location, and it worked perfectly.

**Comment by DavidMoritz** [comment]
essentially, the "dist" folder contents populate the "public_html" folder of your server. Then, all the pathing works because everything is at the root level

**Comment by tpitman** [comment]
I am using a local raspbian (debian) server running LAMP as well. Being raspbian I am hoping I have good versions of things.

I copied everything from dist into root. Now when I browse there I get the pages. There are errors, however.

It takes me to the main page and I hit create ballot. I enter a name and hit submit and nothing happens, but I do get an exception in the console. Here is the exception.
angular.js:130 TypeError: $http(...).success is not a function
    at m.MainCtrl.$s.newBallot (main.js:380)
    at fn (eval at compile (angular.js:246), <anonymous>:4:147)
    at e (angular.js:291)
    at m.$eval (angular.js:155)
    at m.$apply (angular.js:156)
    at HTMLFormElement.<anonymous> (angular.js:291)
    at HTMLFormElement.dispatch (angular.js:10)
    at HTMLFormElement.q.handle (angular.js:10)
﻿

​I really really appreciate you working on this because I need it pretty badly. I have been searching for days for something that will basically be turn key web site and yours is the best so far. Others are very much not ready.

Thank you thank you thank you....

**Comment by DavidMoritz** [comment]
It seems that Angular has updated it's $http protocol. Instead of "success", it uses "then"
https://docs.angularjs.org/api/ng/service/$http

Well that's awfully nice to say. I hope when this is all up and running that I'll earn a star from you!

**Comment by tpitman** [comment]
You will win many stars.

The other thing I will need to do with it, however, is add the ability to register voters so they can only vote once.

If you don't have time to do that, then I can dive into your code and try to figure that out.

**Comment by DavidMoritz** [comment]
I have that ability currently commented out because it's only 95% of the way there. I already have, built-in (currently commented) the ability to sign in with Facebook or Gmail. It was working pretty well, but not production worthy. Check out lines 16 - 39 of app.js

**Comment by DavidMoritz** [comment]
uncomment line 14 of index.jade and take a look at the "register" page. It's mostly there. Anything you want to do to get it the rest of the way would be awesome!

**Comment by tpitman** [comment]
Awesome.

I went in and changed all instances of success to then in the main.js file and ran it again. Now it lets me create the ballot and enter the candidates.

When I hit submit all entries I get this exception:

angular.js:130 TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at cb (angular.js:24)
    at Df.a.defaults.transformRequest (angular.js:104)
    at angular.js:104
    at q (angular.js:14)
    at xd (angular.js:104)
    at angular.js:108
    at angular.js:141
    at m.$digest (angular.js:152)
    at m.$apply (angular.js:156) "Possibly unhandled rejection: {}"

**Comment by DavidMoritz** [comment]
This may be too simplistic, but I hope you didn't blindly replace all instances of "success" with "then". It only needs to change on lines 328, 365, and 383

**Comment by tpitman** [comment]
My thoughts are for an election night Caucus meeting. I don't want people to have to log in or sign up or anything like that. I was thinking about something simpler:

1. A user comes to the meeting and signs in
2. They are given a random, but unique code at the sign in table.
3. A worker enters that code into the system and it is recorded so it can't be generated again.
4. When voting time comes each voter enters their code and the system only allows one vote per code.

This relies on the voter keeping their code secret, which is fine for my use.

Optionally you could allow the person to change their vote up until the voting is done, but it only records the last one as the actual vote. This allows people to change their minds until voting closes.

**Comment by tpitman** [comment]
LOL, I did change all of them. I will revert and change just those lines. thanks for your patience.

**Comment by DavidMoritz** [comment]
I really like your idea of the unique code approach! To me, the simplest way to accomplish this would be to create another table with ballotId and unique code.

**Comment by tpitman** [comment]
I might have slightly different code. There are other places with $http(...).success like line 53.

Also the first one you mention is 328, for me it is 326.

**Comment by tpitman** [comment]
I just barely got the code about an hour ago.

**Comment by DavidMoritz** [comment]
ok, you are correct, I was reading the number wrong. The places of "success" are 55, 328, 365, and 383

**Comment by tpitman** [comment]
I reverted back to the main.js with success in it. I went through the success entries again and changed the 3 lines you mentioned (adjusted a little because they were different). I also changed line 53 because it was part of $http(...).

I am still getting

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at cb (angular.js:24)
    at Df.a.defaults.transformRequest (angular.js:104)
    at angular.js:104
    at q (angular.js:14)
    at xd (angular.js:104)
    at angular.js:108
    at angular.js:141
    at m.$digest (angular.js:152)
    at m.$apply (angular.js:156) "Possibly unhandled rejection: {}"

**Comment by DavidMoritz** [comment]
So, this is happening on line 379 of main.js
Can you put a breakpoint and inspect to see what "$s.candidates" is at that moment?

**Comment by tpitman** [comment]
What should that line say? I think my code is different.

**Comment by tpitman** [comment]
for me stringify is used on line 429

**Comment by DavidMoritz** [comment]
So, trying to debug remotely isn't easy, but it looks like "JSON.stringify" is running into a problem. That is only found on line 379 (of the raw file; 429 of the compiled file) when I take the array of candidates and stringify it before inserting it into the database.

**Comment by DavidMoritz** [comment]
Put a breakpoint on line 425 (of the compiled file) and look at "$s.candidates" in the console to see if it's a simple array or something complex

**Comment by tpitman** [comment]
I understand about remote debugging. Hate it. Never works well.

It is not hitting that break point because that is inside the submitVote. That doesn't make sense because I am hitting the Submit All Entries when trying to create a ballot. I am not even to voting yet.

**Comment by DavidMoritz** [comment]
OH! I think I know. And shame on me for not thinking of this earlier. My guess is that the database needs to be built property before any of this is going to work!

**Comment by DavidMoritz** [comment]
I need to provide the schema so someone creating a new database can just run it and have it work

**Comment by tpitman** [comment]
I was just starting to think about that. I went to my database and noticed there are not any tables in it.

Let me know when you have the schema and I will try again. Now rush. Tomorrow or whenever is fine.

Thanks again...

**Comment by DavidMoritz** [comment]
https://github.com/DavidMoritz/rcv/blob/master/Schema.sql
try that

**Comment by tpitman** [comment]
I have the db with tables now. It created an entry in the ballots table that looks correct. Nothing in the entries table and I am still getting that darn stringify exception :-(

**Comment by tpitman** [comment]
Where do you store the short code? I don't see it in the db anywhere.

**Comment by DavidMoritz** [comment]
I suggest using another method. The goal is to create a string from an array. You could do this by making a string that starts with "[", loop through $s.candidates and append each entry to the string, wrapping each entry in quotes, then adding "]" to the end

**Comment by tpitman** [comment]
The thing is we are never hitting the stringify line of code.

**Comment by DavidMoritz** [comment]
There must be another place its used then. The stack you gave me didn't
reference any of my code, did it? Put a break point right when you click
"submit" and walk through the code slowly until it breaks

**Comment by tpitman** [comment]
Sadly it gets into the minified angular code and I can't follow it very well.

I did remove your use of stringify and just put vote: '' just as a test and still get the exception, so something weird is going on. Not sure what to do at this point.

**Comment by tpitman** [comment]
I need to head home. Let me know tomorrow if you find anything...

**Comment by DavidMoritz** [comment]
OK! I think I figured it out for real this time! I originally built this app quite a while ago and I mistakenly had "latest" as all the version numbers. I have replaced those with the versions that were still sitting in my local version way back when. You'll have to pull the latest changes from master, then run
npm update
bower update
but you should be good to go after that!

**Comment by tpitman** [comment]
I am not at that computer now. I will try it first thing in the morning and let you know.

Thank you

**Comment by DavidMoritz** [comment]
Oh, the "shortcode" is the "key" in the ballot table.
I look forward to seeing your implementation of the unique code concept!

I envision a file called api/code.php that receives a GET param of "ballotId". The api adds an entry to the codes table and returns the generated code. You would also need to add a column in the votes table for the unique code and make (ballotId, code) be a unique index. Make sure you modify api/vote.php accordingly so that the provided code must match an entry in the codes table.
You could also add other information like the username of the worker who generated the code and a timestamp.

I am from Iowa and went to the presidential caucus. The system was ridiculous. We were handed a colored index card (the color representing our district) and told to write the name of the person on it. They had no way, once inside, to determine if someone had brought additional index cards in their pocket to vote additional times. And, they would have had to read thousands of peoples' handwritten names to tally the votes!

I think you are very wise to take an electronic approach and wise to use RCV. I definitely want to help make this happen for you. Great street cred!

Also, if you don't mind, I'd like to receive an email from you (davidmoritz@gmail.com) detailing more information like where you are holding this, what kind of environment, expected attendance etc.

**Comment by tpitman** [comment]
I did a clean checkout of your code. I am running npm install. It is asking me the following during the bower install. How should I answer:


Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#1.5.3 which resolved to 1.5.3 and is required by init-angular
    2) angular#1.6.4 which resolved to 1.6.4 and is required by angular-animate#1.6.4
    3) angular#>=1.4.0 which resolved to 1.6.4 and is required by angular-bootstrap#1.2.5
    4) angular#^1.2.27 which resolved to 1.6.4 and is required by ng-pattern-restrict#0.2.3
    5) angular#>=1.2.x which resolved to 1.6.4 and is required by angular-ui-sortable#0.13.4

Prefix the choice with ! to persist it to bower.json

? Answer

**Comment by tpitman** [comment]
I decided to choose 1.6.4 since it was the latest.

Now I am getting the exception about success is not a function. Did I choose the wrong version of angular?

What now?

**Comment by DavidMoritz** [comment]
I'd suggest 1.5.3. I don't remember using angular animate for anything

**Comment by DavidMoritz** [comment]
That's the version being used in rankedchoices.com

**Comment by DavidMoritz** [comment]
Also, I updated the README with consumption instructions. Please have a look at those and feel free to correct any confusing wording.

**Comment by tpitman** [comment]
So i have it mostly working. I can create a ballot, add entries and everything shows up in the db.

When I enter a code into vote now or results, however, it keeps saying it can't find the code or the time is wrong.

I get-candidates is returning the error string.

I took the query and manually ran it in mysql workbench and it comes back with results.

Any suggestions on how to debug this?

**Comment by tpitman** [comment]
One thing I tried was to modify the get-candidates.php code with some debugging type output. I changed the query and the error message.

The error message that came back was still the same?????

I restarted apache with /etc/init.d/apache2 restart and it said it restarted, but the php change didn't seem to take.

Any idea?

**Comment by DavidMoritz** [comment]
When I debug the api, I put a breakpoint at the place before sending, (to see the info being sent) and one on return (to see the response). If the sending looks good and the response is bad, I then adjust my api file to do things like "echo $variable" and such and look at what it says.

**Comment by DavidMoritz** [comment]
Are you sure you are modifying the file in the correct location? Like, modifying in dist/ or src/ won't do you any good for live edits.

**Comment by DavidMoritz** [comment]
Here's a thought. Run your page parallel with RankedChoices.com. Go there and open the main.js file. Put a breakpoint on lines 254 and 256. Type "tues" in the shortcode and press enter. Verify that "tues" is listed as the $s.shortcode and look at the resp on 256. 
Each step, do the same in your environment and see if anything is different.

**Comment by tpitman** [comment]
yea, modifying the one in /var/www/html/api

**Comment by tpitman** [comment]
Now this is getting really weird.

I did that on your site and it works fine. tues is shown as the short code and the results of the api call are the array of entries as it should be.

I have a ballot in my db with a short code of 3gop. I put that in and it gives the error.

I manually changed the short code of that SAME ballot to tues just for the fun of it. When I do that the query WORKS!!!???

If I manually change the short code of the same ballot back to 3gop, IT FAILS.

If I copy the query from the php code into mysql workbench and query for 3gop it WORKS.

I am totally confused.

**Comment by DavidMoritz** [comment]
Are you somehow pointing to my DB?

**Comment by DavidMoritz** [comment]
I was able to store a shortcode of "3gop" in my DB without any problem.

**Comment by DavidMoritz** [comment]
So, does "gop3" work? Does it just not like it starting with a number for some odd reason?

**Comment by tpitman** [comment]
suddenly my modified php started being run and has an error (forgot a ;) now I can't get it to use the fixed version. Something with caching I am sure.

I will try the idea of starting with a number once I figure out how to clear the php cache.

**Comment by DavidMoritz** [comment]
Well, it sounds like you are really close! Worst case, you only use shortcodes that don't include a number. I've never had an issue with php caching, but I guess you could send additional GET params like "&v=263" to break any client-side caching.

**Comment by DavidMoritz** [comment]
Or, perhaps you need to restart Apache every time you change the file, idk

**Comment by tpitman** [comment]
LOLOLOL, you are going to love this.

What happens after you create a ballot and submit the entires? It takes you to a page that gives you the url to send to people along with a link to click on for you to vote.

What do those have as a url? Not the ip address of the server I am running locally. They have rankedchoices.com. I have been click on that.

I am an idiot.

Sorry for that. Might be a nice change, however, to use the local URL when building those links instead of your hard coded url. Otherwise the site will always redirect to your web site and not the web site that is running your code.

**Comment by tpitman** [comment]
That also answers why my changes to the php were not taking. I wasn't even pointing at my site when I was trying to run them. I was not really looking at the address line in my browser this whole time.

**Comment by DavidMoritz** [comment]
Oh! of course. I didn't think about that. lol
Sorry about that

**Comment by tpitman** [comment]
Question. How do I set a ballot to be done if I didn't give a cut off time?

**Comment by DavidMoritz** [comment]
So, this goes to the registered user ideas that I was creating. I had a profile page that included all the ballots a particular registered user had created and gave that person the ability to clear votes, cut it off, edit candidates, etc. But none of that works if they person makes the ballot anonymously. I suggest uncommenting the code that relates to additional features for registered users and take a look at the GUI I created. If you have any improvements, please submit a PR!
But, without any adjustment to the current code, the simplest way to do that on the fly would be to set the vote-cutoff to be in the past manually in the db.

**Comment by DavidMoritz** [comment]
remove the "//-" on line 14 of index.jade and rebuild to see what I am referring to.

**Comment by tpitman** [comment]
Sounds good. I will take a look at this and let you know if I come up with anything.

I think having users for admin type stuff is needed. I then think having voters as a separate things is also what I will need.

I still owe you an email. I will send that now so you have a better idea of my situation. It is Caucus night for our local party. I am a precinct chair and district chair and am trying to come up with a better way to vote at caucus night.

I am basing it all on the Raspberry Pi because they are cheap. I will give more detail in my email....

**Comment by DavidMoritz** [comment]
Oh, also remove the class ".hidden" from line 22 of src/jade/partials/form.jade

**Comment by tpitman** [comment]
btw, what is the "waiting" task that happens at the end of the grunt command? It just sits there forever. What is it waiting for? I usually just ctrl-c it to get it to end

**Comment by DavidMoritz** [comment]
If you make any changes to the src/ folder, it will automatically rebuild the dist/ folder

**Comment by tpitman** [comment]
oh, so you leave that running if you what auto build. cool.

**Comment by tpitman** [comment]
i see the register stuff in the source index.html, but it still is not showing up in the site.

**Comment by DavidMoritz** [comment]
Maybe there's still a hidden class or something? Try viewing in the
console. Make sure it's not cached

**Comment by tpitman** [comment]
Good call. There is an exception, though I don't have enough experience to know why:

cb=gapi.loaded_0:70 Uncaught 
Object {error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://10.48.10…itelist this origin for your project's client ID."}
details
:
"Not a valid origin for the client: http://10.48.10.43 has not been whitelisted for client ID 828084230115-98814hb54sbrs34jjiecfirgak4svths.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
error
:
"idpiframe_initialization_failed"
__proto__
:
Object
(anonymous)	@	cb=gapi.loaded_0:70

**Comment by tpitman** [comment]
Looks like maybe a local ip can't be used in the google api for users?

**Comment by DavidMoritz** [comment]
oh, I see. It's that when you sign into Google or Facebook, you need to have an account that actually specifies where the app is located. In order for this to work, you need to create a Google and Facebook developer account and create an new project, then use the credentials of that project in your calls as well as represent your ip address on the whitelist.

**Comment by tpitman** [comment]
Thought that might be the case.

I think I might work on the scenario that I emailed to you and not use those credentials.

I will keep you posted.

**Comment by tpitman** [comment]
I sent you that email. Let me know if you didn't get it.

**Comment by DavidMoritz** [comment]
I got it! Just finished reading. Thank you for sending it! I was at lunch with a friend, but I'll reply soon.

**Comment by tpitman** [comment]
I guess we do have to eat lunch once in a while :-)

**Comment by tpitman** [comment]
Let me know if I should start a new issue thread for this:

I am wondering about the random selection to eliminate candidates. Is this the main standard way or did you just choose it because it is easy to implement?

What are the other options? I read about eliminating all candidates who tie when they are all lower than the rest of the candidates (tie for lowest votes all get dropped and reallocated).

How hard would it be to implement that version? That one seems more "fair". I can see people getting upset about a random number being used.

**Comment by DavidMoritz** [comment]
You are referring to the topic of the only other issue thread on my repo! lol

Please review the dialogue I had with Paul Lockett:
https://github.com/DavidMoritz/rcv/issues/1

Although it's counter-intuitive random really is the most fair. Keep in mind, ties are extremely rare and typically, the other candidate is the next one out anyway, rending the order of the tie resolution moot.

That being said, it's important to remember the one of the core philosophies of RCV is "No Tactical Voting". Paul Lockett makes a good case that if there is a method anything other than random, that could lead to people voting tactically, rather than honestly. But, with random, there is no such value is anything but honesty.

Again, the shear odds of two candidates having a tie for last and the outcome of a random determination of the order of their dismissal having any changed outcome on the final result in a legitimate election are staggeringly low.

**Comment by DavidMoritz** [comment]
Also, making a randomizer that provides consistent results for front-end consumption is not easier to implement.

**Comment by tpitman** [comment]
Sounds like using a random selection like you do now is actually preferred. That is good. I wonder if there are any good sites explaining that using a random pick is official.

One of the things I am planning when using this is to show some short videos that explain RCV so people know will will happen. If you know of one that includes using random tie breaking, I will use that.

**Comment by DavidMoritz** [comment]
https://youtu.be/l8XOZJkozfI
That's a great video for it!

However, they call it "single transferable vote" (the older, less popular name) and they go more into detail about the value for multi-winner elections rather than being more instructional in nature.

**Comment by DavidMoritz** [comment]
But, I was thinking it would be cool to have an advanced option for tie-break method. Something like:

Random(official) ... Weighted ... No Winner

Then, the person making the pole can determine for themselves how they want to deal with tie-breaks.

**Comment by tpitman** [comment]
That is even better.

I think I watched that video after first coming to your github site. I found a couple others, but none of them talk about ties.

Implementing it as options would be best.

**Comment by DavidMoritz** [comment]
I appreciate you bringing this up! I have supplied instructions in the README file for proper consumption. Closing.

**Comment by DavidMoritz** [comment]
Adding "Implemented" because this was the original spark for what is now the Secure Ballot feature, even with the double-blind nature of passing out pre-determined codes!
